apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fcp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/deepakann/FilmCastPro.git"
    targetRevision: master
    path: helm/fcp-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
