apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filmcastpro-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vimalathanga/FilmCastPro_Deepa.git'
    targetRevision: feature/helm-argocd
    path: helm/filmcastpro-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: batch
      kind: Job
      name: filmcastpro-frontend-smoketest
      jsonPointers:
        - /status
